#### Author : Riasad Alvi
#### 17 Feb 2025



### **NumPy (Numerical Python)**  

✅ **What is NumPy?**  
A powerful Python library for numerical computing, providing support for large multi-dimensional arrays, matrices, and high-level mathematical functions.  

---

✅ **What Does It Do?**  
- **Efficient Array Handling**: Works with n-dimensional arrays (ndarrays) for fast data manipulation.  
- **Mathematical Operations**: Performs linear algebra, statistical functions, and complex mathematical computations.  
- **Broadcasting**: Allows operations on arrays of different shapes without manual looping.  
- **Data Integration**: Works seamlessly with other scientific libraries (e.g., SciPy, Pandas, TensorFlow).  

---

✅ **When to Use It?**  
- **Large Data Manipulation**: Handling massive datasets efficiently.  
- **Numerical Computations**: When you need fast matrix operations, Fourier transforms, or random sampling.  
- **Performance-Critical Code**: Replacing native Python loops for better speed using vectorized operations.  

---

✅ **Why Is It Useful?**  
- **Speed**: Significantly faster than standard Python lists (optimized in C).  
- **Memory Efficiency**: Consumes less memory due to optimized data structures.  
- **Versatility**: Useful for machine learning, scientific computing, and statistical analysis.

### Creating Numpy Arrays

In [7]:
# np.array
import numpy as np

a = np.array([1,2,3])  # 1D / Vector
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
# Creating a 2D NumPy array (matrix)
b = np.array([[1,2,3],[4,5,6]])
print(b)

# Shape: (2, 3) -> 2 rows, 3 columns



[[1 2 3]
 [4 5 6]]


In [12]:
# Creating a 3D NumPy array (tensor)
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,22]]])
print(c)

# Shape: (2, 2, 3) -> (depth, rows, columns)
# Two blocks, each with 2 rows and 3 columns

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 22]]]


In [13]:
# Creating a NumPy array with a specific data type (float)
a = np.array([1,2,3], dtype=float)

# Elements are stored as floating-point numbers (1.0, 2.0, 3.0)
print(a)

[1. 2. 3.]


In [15]:
# Creating a NumPy array with values from 1 to 10 (step of 2)
a = np.arange(1, 11, 2)
print(a)

[1 3 5 7 9]


In [16]:
# Creating a NumPy array with values from 0 to 15 and reshaping it to (2, 2, 2, 2)
a = np.arange(16).reshape(2, 2, 2, 2)

print(a)
# Shape: (2, 2, 2, 2) -> 2 blocks, each with 2 rows, 2 columns, and 2 elements


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [17]:
# Creating a 3x4 array filled with ones
a = np.ones((3, 4))

print(a)
# Output: Array of shape (3, 4) with all elements as 1


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
# Creating a 3x4 array filled with zeros
a = np.zeros((3, 4))

print(a)
# Output: Array of shape (3, 4) with all elements as 0


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# Creating a 3x4 array with random values between 0 and 1
a = np.random.random((3, 4))

print(a)
# Output: Array of shape (3, 4) with random floating-point values


[[0.10515423 0.21054356 0.59137273 0.20180044]
 [0.44726337 0.09952709 0.57083696 0.97696026]
 [0.63287969 0.97845841 0.07226347 0.52975534]]


In [20]:
# Creating an array of 10 evenly spaced integers from -10 to 10
a = np.linspace(-10, 10, 10, dtype=int)

print(a)
# Output: Array of 10 integers from -10 to 10, inclusive


[-10  -8  -6  -4  -2   1   3   5   7  10]


In [21]:
# Creating a 3x3 identity matrix
a = np.identity(3)

print(a)
# Output: 3x3 matrix with 1s on the diagonal and 0s elsewhere


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [22]:
# Creating and reshaping arrays
a1 = np.arange(10, dtype=np.int32)  # 1D array with 10 elements of type int32
a2 = np.arange(12, dtype=float).reshape(3, 4)  # 2D array with shape (3, 4), type float
a3 = np.arange(8).reshape(2, 2, 2)  # 3D array with shape (2, 2, 2)

print(a3)
# Output of a3: 3D array with shape (2, 2, 2)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
# Checking the number of dimensions of the array a3
a3.ndim

# Output: 3 (since a3 is a 3D array)


3

In [60]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
# Checking the shape of the array a3
print(a3.shape)

# Output: (2, 2, 2) -> 2 blocks, each with 2 rows and 2 columns


(2, 2, 2)


In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# Checking the total number of elements in the array a2
print(a2.size)

# Output: 12 (since a2 has 3 rows and 4 columns, 3 * 4 = 12)

12


In [62]:
# Checking the size in bytes of each element in the array a3
a3.itemsize

# Output: 8 (since a3 contains int64 elements, each takes 8 bytes)

8

In [64]:
# Checking the data type of each array
print(a1.dtype)  # Output: int32
print(a2.dtype)  # Output: float64
print(a3.dtype)  # Output: int64


int64
int64
int64


### Changing Datatype

In [28]:
# Converting the data type of a3 to int32
a3.astype(np.int32)

# Output: a3 with elements converted to int32 data type


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [71]:
# Creating two arrays :
a1 = np.arange(12).reshape(3, 4)  # a1: 3 rows, 4 columns, values from 0 to 11
a2 = np.arange(12, 24).reshape(3, 4)  # a2: 3 rows, 4 columns, values from 12 to 23

print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


##### Scaler operations -> operations on a single numpy array :

In [66]:
# Arithmetic :

# Performing element-wise squaring of each element in a1
a1 ** 2

# Output: Each element in a1 raised to the power of 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [67]:
# Relational :

# Checking where elements in a2 are equal to 15
a2 == 15

# Output: Boolean array indicating True where element is 15, False otherwise


array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

##### Vector Oparations -> operations between two or more numpy arrays :

In [69]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [33]:
# Performing element-wise exponentiation of a1 to the power of a2
a1 ** a2

# Output: Each element in a1 raised to the power of the corresponding element in a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [75]:
# Generate a 3x3 array with random values between 0 and 1
a1 = np.random.random((3, 3))

# Multiply each element by 100 and round to the nearest integer
a1 = np.round(a1 * 100)

a1

# Output: A 3x3 array with random integers between 0 and 100

array([[77., 64., 80.],
       [81., 12., 96.],
       [26., 78., 79.]])

In [76]:
np.max(a1)

96.0

In [77]:
np.min(a1)

12.0

In [78]:
np.sum(a1)

593.0

In [79]:
np.prod(a1)

5893770573250560.0

In [84]:
# Compute the mean (average) of all elements in the array a1
np.mean(a1)

# Output: A single value representing the average of all elements in a1

65.88888888888889

In [85]:
# Compute the median (middle value) of all elements in the array a1
np.median(a1)

# Output: A single value representing the median of all elements in a1

78.0

In [86]:
# Compute the variance (measure of spread) of all elements in the array a1
np.var(a1)

# Output: A single value representing the variance of all elements in a1

697.2098765432098

In [87]:
# Compute the standard deviation (square root of variance) of all elements in the array a1
np.std(a1)

# Output: A single value representing the standard deviation of all elements in a1

26.404732086185042

In [80]:
a1

array([[77., 64., 80.],
       [81., 12., 96.],
       [26., 78., 79.]])

In [36]:
# Calculating the product of elements along each column (axis=0)
np.prod(a1, axis=0)

# Output: Array with the product of each column

array([ 53550.,  94116., 178500.])

In [81]:
np.max(a1,axis=0)

array([81., 78., 96.])

In [37]:
# Calculating the variance of elements along each row (axis=1)
np.var(a1, axis=1)

# Output: Array with the variance of each row

array([ 34.66666667, 150.22222222,  80.22222222])

In [39]:
# Create a 3x4 array with values from 0 to 11
a2 = np.arange(12).reshape(3,4)

# Create a 4x3 array with values from 12 to 23
a3 = np.arange(12,24).reshape(4,3)

# Compute the dot product of a2 and a3 (3x4 dot 4x3 results in a 3x3 matrix)
np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [88]:
np.log(a1)

array([[4.34380542, 4.15888308, 4.38202663],
       [4.39444915, 2.48490665, 4.56434819],
       [3.25809654, 4.35670883, 4.36944785]])

In [40]:
# Compute the exponential of each element in array a1
np.exp(a1)


array([[1.31881573e+09, 2.90488497e+13, 1.58601345e+15],
       [1.06864746e+13, 9.49611942e+19, 1.14200739e+26],
       [8.22301271e+36, 4.60718663e+28, 8.22301271e+36]])

In [89]:
# Generate a 2x3 array with random values between 0 and 1
# Multiply each element by 100 and round to the nearest integer
np.round(np.random.random((2,3)) * 100)

# Output: A 2x3 array with random integers between 0 and 100


array([[33., 23., 49.],
       [79., 31.,  6.]])

In [41]:
# Generate a 2x3 array of random values between 0 and 1, multiply by 100
# Then apply the ceiling function to round up each value to the nearest integer
np.ceil(np.random.random((2,3))*100)


array([[74., 55., 87.],
       [27., 38., 86.]])

### Indexing and Slicing

In [90]:
# Create a 1D array with values from 0 to 9
a1 = np.arange(10)

# Create a 3x4 array with values from 0 to 11
a2 = np.arange(12).reshape(3,4)

# Create a 2x2x2 3D array with values from 0 to 7
a3 = np.arange(8).reshape(2,2,2)


In [43]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a1[0]

0

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
# Access the element in the second row, first column of array a2
a2[1,0]

4

In [46]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
# lets say we want to access -> 5
# its in -> 2nd 2D array so 1 , in that 2D array first row so 0 , in that 2D array second col so 1
# Access the element in the second 2D array, first row, second column of the 3D array a3
a3[1,0,1]


5

In [48]:
a3[1,1,0]

6

### Slicing :

In [49]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a1[2:5]

array([2, 3, 4])

In [51]:
# Slice the array a1 from index 2 to index 5 (exclusive), with a step of 2
# "exclusive" means that the end index is not included in the slice
a1[2:5:2]

array([2, 4])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
# a2[row ? , col ? ]
# i want first row and all cols of that row  :

a2[0,:]

array([0, 1, 2, 3])

In [101]:
# i want 3rd col and all rows of that col  :
a2[:,2]

array([ 2,  6, 10])

In [102]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
"""
I want :
5, 6
9, 10
"""

a2[1:,1:3]


array([[ 5,  6],
       [ 9, 10]])

In [106]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
"""
I want :
0, 3
8, 11
"""
# a2[from first row make 2 jump , from first col make 3 jump]
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [109]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
"""
I want :
1, 3
9, 11
"""

a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [112]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [113]:
"""
I want :
2nd 2D array
"""
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [114]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
"""
I want :
1st and last 2D array
"""
a3[::2]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
"""
I want :
3, 4, 5
"""
# a3[which 2D array , which rows , which cols]
a3[0,1,:]

array([3, 4, 5])

In [121]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
"""
I want :
10, 13, 16
"""
# a3[which 2d array , which rows , which cols]
a3[1,:,1]

array([10, 13, 16])

In [127]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [130]:
"""
I want :
22, 23
25, 26
"""
# a3[which 2d array , which rows , which cols]
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

### Iterating

In [131]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [135]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [137]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [138]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [140]:
# Iterate over each element in the 3D array a3 using nditer (flattening it)
for i in np.nditer(a3):
    print(i)

# Output: Each element of a3 printed one by one in a flattened order

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [141]:
# reshape -> Done

In [142]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
# Transpose the array a2 (swap rows and columns)
a2.T

# Output: Transposed version of a2 where rows become columns and vice versa

# Alternative way to transpose using np.transpose
#np.transpose(a2)  # This also works the same way


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [147]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [146]:
# Flatten the 3D array a3 into a 1D array
a3.ravel()

# Output: A 1D array containing all elements of a3 in row-major order

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [148]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [149]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [151]:
# Horizontally stack (concatenate) the arrays a4 and a5
np.hstack((a4, a5))

# Output: A new array where a5 is appended to a4 along the columns, resulting in a (3, 8) shape

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [152]:
# Vertically stack (concatenate) the arrays a4 and a5
np.vstack((a4, a5))

# Output: A new array where a5 is appended to a4 along the rows, resulting in a (6, 4) shape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [153]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###### Horizontal Splitting :

In [157]:
# Horizontally split the array a4 into 2 equal parts
np.hsplit(a4, 2)

# Output: A list of 2 arrays, each containing half of the columns of a4

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [158]:
# Split the array a4 into 4 equal sub-arrays along the columns
np.hsplit(a4, 4)

# Output: A list of 4 sub-arrays, each containing 1 column from a4

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [161]:
np.hsplit(a4, 5) # error -> has to be equa on each part

ValueError: array split does not result in an equal division

###### Vertical Splitting :

In [159]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [162]:
# Split the array a5 into 3 equal sub-arrays along the rows
np.vsplit(a5, 3)

# Output: A list of 3 sub-arrays, each containing 1 row from a5

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [163]:
# Split the array a5 into 2 equal sub-arrays along the rows
np.vsplit(a5, 2)

# Output: A list of 2 sub-arrays, each containing 2 rows from a5


ValueError: array split does not result in an equal division

The error occurs because the array `a5` has 3 rows, and you are trying to split it into 2 equal parts along the rows. For `np.vsplit()` to work, the number of rows must be divisible by the number of splits.

In this case, `a5` has 3 rows, and trying to split it into 2 parts is not possible without a remainder. You can only split an array into a number of parts that evenly divides the number of rows.

To fix the error, you can split it into 3 parts, like so:

```python
np.vsplit(a5, 3)
```

Alternatively, you could ensure that the number of rows is divisible by the number of parts you'd like to split it into.